{-# OPTIONS --cubical --guardedness #-}

-- ==========================================================================
--
-- AxiomsWork: The axioms of Synthetic Stone Duality and their consequences
--
-- This file presents the axiom system from main-monolithic.tex
-- (Section 1.2, "Axioms", lines 280-353) and derives the key
-- consequences: Markov's Principle, LLPO, and ¬WLPO.
--
-- OUTLINE
--   1. Stone Duality Axiom (tex Axiom AxStoneDuality)
--   2. Surjections are Formal Surjections (tex Axiom SurjectionsAreFormalSurjections)
--   3. Local Choice (tex Axiom AxLocalChoice)
--   4. Dependent Choice (tex Axiom axDependentChoice)
--   5. Consequence: Markov's Principle (tex Theorem MPfromSD)
--   6. Consequence: LLPO (tex Theorem LLPO)
--   7. Consequence: ¬WLPO (tex Theorem NotWLPO)
--   8. Summary of postulates
--
-- ==========================================================================

module work.AxiomsWork where

-- Import Part02, which transitively provides everything from Part01.
-- The 'public' re-export makes all Part01/Part02 definitions available
-- to any module that imports AxiomsWork.
open import work.Part02 public

-- ==========================================================================
--
--  1. STONE DUALITY AXIOM (tex Axiom AxStoneDuality, line 282)
--
-- ==========================================================================
--
-- The Stone Duality Axiom states that for every countably presented
-- Boolean algebra B : Booleω, the evaluation map
--
--     eval_B : ⟨ B ⟩ → (Sp B → Bool)
--
-- is an equivalence.  Here Sp B is the spectrum of B, i.e., the type
-- of Boolean ring homomorphisms B → 2.
--
-- Re-exported from Part02/Axioms.StoneDuality:
--   StoneDualityAxiom : Type (ℓ-suc ℓ-zero)
--   Sp     : Booleω → Type ℓ-zero          (spectrum functor)
--   Booleω : Type (ℓ-suc ℓ-zero)           (countably presented Boolean algebras)
--   SpEmbedding : StoneDualityAxiom → isEmbedding Sp
--
-- Postulated axiom:
--   sd-axiom : StoneDualityAxiom            (Part02, line 835)

-- ==========================================================================
--
--  2. SURJECTIONS ARE FORMAL SURJECTIONS (tex Axiom SurjectionsAreFormalSurjections, line 294)
--
-- ==========================================================================
--
-- For all morphisms g : B → C in Booleω:
--   g is injective  ⟺  Sp(g) is surjective.
--
-- This axiom connects algebraic injectivity to topological surjectivity,
-- and is essential for the LLPO proof.
--
-- Re-exported from Part02:
--   SurjectionsAreFormalSurjectionsAxiom : Type (ℓ-suc ℓ-zero)
--   surj-formal-axiom : SurjectionsAreFormalSurjectionsAxiom
--   isInjectiveBoolHom  : (B C : Booleω) → BoolHom (fst B) (fst C) → Type ℓ-zero
--   isSurjectiveSpHom   : (B C : Booleω) → BoolHom (fst B) (fst C) → Type ℓ-zero
--   Sp-hom              : (B C : Booleω) → BoolHom (fst B) (fst C) → Sp C → Sp B
--   injective→Sp-surjective : ...  (forward direction)
--   Sp-surjective→injective : ...  (backward direction)

-- ==========================================================================
--
--  3. LOCAL CHOICE (tex Axiom AxLocalChoice, line 348)
--
-- ==========================================================================
--
-- For all B : Booleω and type family P over Sp(B), if
--   (s : Sp B) → ∥ P s ∥₁
-- then there merely exists C : Booleω, a surjection q : Sp C → Sp B,
-- and untruncated witnesses (t : Sp C) → P (q t).
--
-- This axiom allows "pulling back along a surjection" to eliminate
-- propositional truncation.
--
-- Re-exported from Part02:
--   LocalChoiceAxiom  : Type (ℓ-suc ℓ-zero)
--   localChoice-axiom : LocalChoiceAxiom
--   SpTypeFamily      : Booleω → Type (ℓ-suc ℓ-zero)
--   isSurjectiveSpMap : {B C : Booleω} → (Sp C → Sp B) → Type ℓ-zero

-- ==========================================================================
--
--  4. DEPENDENT CHOICE (tex Axiom axDependentChoice, line 324)
--
-- ==========================================================================
--
-- For all types (Eₙ)_{n:ℕ} with surjections E_{n+1} ↠ Eₙ,
-- the projection from lim_k Eₖ to E₀ is surjective.
--
-- Re-exported from Part02:
--   DependentChoiceAxiom  : Type (ℓ-suc ℓ-zero)
--   dependentChoice-axiom : DependentChoiceAxiom
--   SeqLimit   : (E : ℕ → Type ℓ-zero) → ((n : ℕ) → E (suc n) → E n) → Type ℓ-zero
--   seqLim-proj₀ : ...
--
-- Derived:
--   CountableChoiceAxiom : Type (ℓ-suc ℓ-zero)
--   countableChoice      : CountableChoiceAxiom
--                          (derived from DependentChoice, Part02 line 946)

-- ==========================================================================
--
--  5. CONSEQUENCE: MARKOV'S PRINCIPLE (tex Theorem MPfromSD, line 459)
--
-- ==========================================================================
--
-- For all α : 2^ℕ:
--   ¬(∀ n, α n = false) → Σ[ n ∈ ℕ ] α n = true
--
-- Proof sketch (from tex, lines 459-468):
--   1. ¬(∀n. αn = false) means Sp(2/α) is empty (MarkovLib.emptySp).
--   2. Stone Duality (Sp is an embedding) gives 2/α = trivial ring.
--   3. Hence 0 = 1 in 2/α, so true ∈ ideal generated by α.
--   4. By MarkovLib.extract', this yields Σn. αn = true.
--
-- Re-exported from Part02:
--   MarkovPrinciple : Type₀                  (Part01, line 347)
--   mp              : MarkovPrinciple         (Part02, line 985)
--   mp-from-SD      : StoneDualityAxiom → MarkovPrinciple
--
-- Infrastructure used in the proof:
--   SpectrumEmptyImpliesTrivial : module      (Part02, line 58)
--   quotient-Booleω : binarySequence → Booleω (Part02, line 830)

-- ==========================================================================
--
--  6. CONSEQUENCE: LLPO (tex Theorem LLPO, lines 541-595)
--
-- ==========================================================================
--
-- For all α : ℕ∞ (sequences hitting true at most once):
--   (∀ k, α_{2k} = false) ⊎ (∀ k, α_{2k+1} = false)
--
-- The proof constructs f : B∞ → B∞ × B∞, shows it is injective
-- (via normal forms), then uses SurjectionsAreFormalSurjections to get
-- that Sp(f) is surjective.  Case-splitting on the preimage yields LLPO.
--
-- The full proof with documentation is in work/LLPOWork.agda.
--
-- Re-exported from Part02:
--   LLPO            : Type₀                   (Part01, line 399)
--   llpo            : LLPO                    (Part02, postulate, line 1220)
--   hitsAtMostOnce  : binarySequence → Type₀  (Part01, line 388)
--   ℕ∞              : Type₀                   (Part01, line 396)

-- ==========================================================================
--
--  7. CONSEQUENCE: ¬WLPO (tex Theorem NotWLPO, line 475)
--
-- ==========================================================================
--
-- ¬ ∀ α : 2^ℕ, ((∀ n, α n = false) ∨ ¬(∀ n, α n = false))
--
-- Proof sketch (from tex, lines 475-497):
--   1. Assume f : 2^ℕ → Bool decides "all zeros":
--        f(α) = false ↔ ∀n. αn = false
--   2. By Stone Duality, f is determined by a Boolean term c
--      using only finitely many generators g₀, ..., gₖ.
--   3. Consider β = 0^ω (all zeros) and γ = 0^k 1 0^ω.
--   4. β and γ agree on g₀, ..., gₖ, so f(β) = f(γ).
--   5. But f(β) should be false and f(γ) should be true.
--   6. Contradiction.
--
-- Re-exported from Part01:
--   WLPO : Type₀                             (Part01, line 359)

-- ==========================================================================
--
--  8. SUMMARY OF POSTULATES
--
-- ==========================================================================
--
-- The axiom system consists of four postulates:
--
--   1. sd-axiom            : StoneDualityAxiom
--      (Stone Duality: eval_B is an equivalence for all B : Booleω)
--
--   2. surj-formal-axiom   : SurjectionsAreFormalSurjectionsAxiom
--      (injective ⟺ Sp-surjective for Boolean algebra morphisms)
--
--   3. localChoice-axiom   : LocalChoiceAxiom
--      (pull back along surjections to eliminate truncation)
--
--   4. dependentChoice-axiom : DependentChoiceAxiom
--      (sequential limit projections are surjective)
--
-- Additional postulates (proof gaps, to be eliminated):
--
--   5. llpo : LLPO
--      (postulated in Part02; proved modulo gaps in LLPOWork.agda)
--
--   6. BoolQuotientEquiv : A /Im (⊎.rec f g) ≡ (A /Im f) /Im (π ∘ g)
--      (postulated in Part01, proved in QuotientConclusions.agda
--       but not imported due to slow compilation)
--
-- Derived principles (not postulated):
--   - mp              : MarkovPrinciple      (from sd-axiom)
--   - countableChoice : CountableChoiceAxiom  (from dependentChoice-axiom)
